"""Voice-session primitives shared by the transport endpoints."""

from .answer_completion import (
    AnswerCompletionController,
    AnswerCompletionState,
)
from .application import VoiceEndpointApplication, VoiceEndpointConfig
from .connection import VoiceConnectionController, VoiceConnectionIO
from .handlers import (
    AgentOutputPresenter,
    AnswerCompletionMessageHandler,
    ClientControlHandler,
    LiveAudioConfig,
    LiveAudioInputHandler,
    ManualAudioBlobProcessor,
    ManualAudioInputHandler,
    ManualInterruptHandler,
    MessageHandlerAction,
    SessionLifecycleHandler,
    SessionResumeHandler,
    SoulXAudioHandler,
    SpeechTurnConfig,
    SpeechTurnProcessor,
    SpeakerVerificationController,
    TextTurnHandler,
    VisionMessageHandler,
    VoiceFeedbackPresenter,
    VoiceInterruptionController,
    VoiceMessageRouter,
    VoiceRouteResult,
)
from .media import (
    WebRTCAssistantAudioTrack,
    WebRTCPeerSession,
    WebRTCVoiceConnection,
)
from .persistence import VoiceAudioStore, VoiceDatasetManifestStore, VoiceHistoryStore
from .realtime_companion import RealtimeCompanion, RealtimeCompanionConfig
from .services import (
    AgentResumeStateService,
    PatientMemoryContext,
    PatientMemoryService,
    PatientProfileService,
    SpeechProcessingCoordinator,
    TTSPrewarmHandle,
    VoiceConnectionCleanup,
    VoiceSessionBootstrap,
    VoiceTTSStreamer,
)
from .runtime import (
    VADBuffer,
    VoiceModelRuntime,
    VoiceRecognitionService,
    audio_is_effectively_silent,
    audio_signal_stats,
    clean_for_tts,
    decode_recorded_audio_blob,
)
from .session import (
    VoiceLifecycleState,
    VoiceProcessingState,
    VoiceRuntimeState,
    VoiceSession,
    VoiceTurnTakingState,
)

__all__ = [
    "AgentOutputPresenter",
    "AgentResumeStateService",
    "AnswerCompletionController",
    "AnswerCompletionState",
    "AnswerCompletionMessageHandler",
    "ClientControlHandler",
    "LiveAudioConfig",
    "LiveAudioInputHandler",
    "ManualAudioBlobProcessor",
    "ManualAudioInputHandler",
    "ManualInterruptHandler",
    "MessageHandlerAction",
    "PatientMemoryContext",
    "PatientMemoryService",
    "PatientProfileService",
    "RealtimeCompanion",
    "RealtimeCompanionConfig",
    "SessionResumeHandler",
    "SessionLifecycleHandler",
    "SoulXAudioHandler",
    "SpeechTurnConfig",
    "SpeechTurnProcessor",
    "SpeechProcessingCoordinator",
    "SpeakerVerificationController",
    "TextTurnHandler",
    "TTSPrewarmHandle",
    "VoiceAudioStore",
    "VoiceConnectionCleanup",
    "VoiceConnectionController",
    "VoiceConnectionIO",
    "VoiceFeedbackPresenter",
    "VoiceDatasetManifestStore",
    "VoiceEndpointApplication",
    "VoiceEndpointConfig",
    "VoiceHistoryStore",
    "VoiceInterruptionController",
    "VoiceLifecycleState",
    "VoiceMessageRouter",
    "VoiceModelRuntime",
    "VoiceRecognitionService",
    "VoiceRouteResult",
    "VoiceProcessingState",
    "VoiceRuntimeState",
    "VoiceSession",
    "VoiceSessionBootstrap",
    "VoiceTTSStreamer",
    "VoiceTurnTakingState",
    "VisionMessageHandler",
    "VADBuffer",
    "WebRTCAssistantAudioTrack",
    "WebRTCPeerSession",
    "WebRTCVoiceConnection",
    "audio_is_effectively_silent",
    "audio_signal_stats",
    "clean_for_tts",
    "decode_recorded_audio_blob",
]
